gfcli:
  gen:
    dao:
    - link:     "mysql:root:root@tcp(192.168.1.4:3306)/osp"
      jsonCase: "CamelLower"
      path:     "./internal"

database:
  default:
    link:  "mysql:root:root@tcp(192.168.1.2:3306)/osp"
    debug: "true"

server:
  ServerRoot: "public"
  address: ":8199"
  openapiPath: "/api.json"

peer:
  port: 9999                # 节点监听端口号
  boots:                    # 加入的网络节点列表
    - addr: "tcp:xxxx"
    - addr: "tcp:xx11122"