// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// App is the golang structure of table app for DAO operations like Where/Data.
type App struct {
	g.Meta   `orm:"table:app, do:true"`
	Id       interface{} //
	Appid    interface{} //
	ApiKey   interface{} //
	SecKey   interface{} //
	Owner    interface{} //
	Name     interface{} // 应用名
	Status   interface{} // 1启用 0 禁用
	OwnerUid interface{} // 拥有者uid
	Created  *gtime.Time //
	Updated  *gtime.Time //
}
