// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// CheckTpl is the golang structure of table check_tpl for DAO operations like Where/Data.
type CheckTpl struct {
	g.Meta      `orm:"table:check_tpl, do:true"`
	Id          interface{} //
	Tid         interface{} // 唯一id
	Name        interface{} // 名称
	Description interface{} // 描述
	Type        interface{} // 类型
	Creater     interface{} // 创建人
	Updater     interface{} // 更新人
	Created     *gtime.Time //
	Updated     *gtime.Time //
}
