// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// TaskPreset is the golang structure of table task_preset for DAO operations like Where/Data.
type TaskPreset struct {
	g.Meta  `orm:"table:task_preset, do:true"`
	Id      interface{} //
	Uuid    interface{} //
	Name    interface{} // 任务名
	Type    interface{} // 任务类型
	Content interface{} // 任务内容
	Peers   interface{} // 主机列表
	Creater interface{} // 创建人
	Created *gtime.Time // 创建时间
	Updated *gtime.Time // 更新时间
}
