// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// CheckTplDao is the data access object for table check_tpl.
type CheckTplDao struct {
	table   string          // table is the underlying table name of the DAO.
	group   string          // group is the database configuration group name of current DAO.
	columns CheckTplColumns // columns contains all the column names of Table for convenient usage.
}

// CheckTplColumns defines and stores column names for table check_tpl.
type CheckTplColumns struct {
	Id          string //
	Tid         string // 唯一id
	Name        string // 名称
	Description string // 描述
	Type        string // 类型
	Creater     string // 创建人
	Updater     string // 更新人
	Created     string //
	Updated     string //
}

//  checkTplColumns holds the columns for table check_tpl.
var checkTplColumns = CheckTplColumns{
	Id:          "id",
	Tid:         "tid",
	Name:        "name",
	Description: "description",
	Type:        "type",
	Creater:     "creater",
	Updater:     "updater",
	Created:     "created",
	Updated:     "updated",
}

// NewCheckTplDao creates and returns a new DAO object for table data access.
func NewCheckTplDao() *CheckTplDao {
	return &CheckTplDao{
		group:   "default",
		table:   "check_tpl",
		columns: checkTplColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *CheckTplDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *CheckTplDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *CheckTplDao) Columns() CheckTplColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *CheckTplDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *CheckTplDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *CheckTplDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
