// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-ops/internal/service/internal/dao/internal"
)

// internalAgentInfoDao is internal type for wrapping internal DAO implements.
type internalAgentInfoDao = *internal.AgentInfoDao

// agentInfoDao is the data access object for table agent_info.
// You can define custom methods on it to extend its functionality as you wish.
type agentInfoDao struct {
	internalAgentInfoDao
}

var (
	// AgentInfo is globally public accessible object for table agent_info operations.
	AgentInfo = agentInfoDao{
		internal.NewAgentInfoDao(),
	}
)

// Fill with you ideas below.
