// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-ops/internal/service/internal/dao/internal"
)

// internalCheckTplDetailDao is internal type for wrapping internal DAO implements.
type internalCheckTplDetailDao = *internal.CheckTplDetailDao

// checkTplDetailDao is the data access object for table check_tpl_detail.
// You can define custom methods on it to extend its functionality as you wish.
type checkTplDetailDao struct {
	internalCheckTplDetailDao
}

var (
	// CheckTplDetail is globally public accessible object for table check_tpl_detail operations.
	CheckTplDetail = checkTplDetailDao{
		internal.NewCheckTplDetailDao(),
	}
)

// Fill with you ideas below.
