// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-ops/internal/service/internal/dao/internal"
)

// internalCheckItemDao is internal type for wrapping internal DAO implements.
type internalCheckItemDao = *internal.CheckItemDao

// checkItemDao is the data access object for table check_item.
// You can define custom methods on it to extend its functionality as you wish.
type checkItemDao struct {
	internalCheckItemDao
}

var (
	// CheckItem is globally public accessible object for table check_item operations.
	CheckItem = checkItemDao{
		internal.NewCheckItemDao(),
	}
)

// Fill with you ideas below.
