// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-ops/internal/service/internal/dao/internal"
)

// internalCronTaskDao is internal type for wrapping internal DAO implements.
type internalCronTaskDao = *internal.CronTaskDao

// cronTaskDao is the data access object for table cron_task.
// You can define custom methods on it to extend its functionality as you wish.
type cronTaskDao struct {
	internalCronTaskDao
}

var (
	// CronTask is globally public accessible object for table cron_task operations.
	CronTask = cronTaskDao{
		internal.NewCronTaskDao(),
	}
)

// Fill with you ideas below.
