// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-ops/internal/service/internal/dao/internal"
)

// internalPluginDao is internal type for wrapping internal DAO implements.
type internalPluginDao = *internal.PluginDao

// pluginDao is the data access object for table plugin.
// You can define custom methods on it to extend its functionality as you wish.
type pluginDao struct {
	internalPluginDao
}

var (
	// Plugin is globally public accessible object for table plugin operations.
	Plugin = pluginDao{
		internal.NewPluginDao(),
	}
)

// Fill with you ideas below.
