// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-ops/service/internal/dao/internal"
)

// internalCheckTplDao is internal type for wrapping internal DAO implements.
type internalCheckTplDao = *internal.CheckTplDao

// checkTplDao is the data access object for table check_tpl.
// You can define custom methods on it to extend its functionality as you wish.
type checkTplDao struct {
	internalCheckTplDao
}

var (
	// CheckTpl is globally public accessible object for table check_tpl operations.
	CheckTpl = checkTplDao{
		internal.NewCheckTplDao(),
	}
)

// Fill with you ideas below.
