// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-ops/service/internal/dao/internal"
)

// internalTaskPresetDao is internal type for wrapping internal DAO implements.
type internalTaskPresetDao = *internal.TaskPresetDao

// taskPresetDao is the data access object for table task_preset.
// You can define custom methods on it to extend its functionality as you wish.
type taskPresetDao struct {
	internalTaskPresetDao
}

var (
	// TaskPreset is globally public accessible object for table task_preset operations.
	TaskPreset = taskPresetDao{
		internal.NewTaskPresetDao(),
	}
)

// Fill with you ideas below.
