// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// CheckTplDetail is the golang structure of table check_tpl_detail for DAO operations like Where/Data.
type CheckTplDetail struct {
	g.Meta `orm:"table:check_tpl_detail, do:true"`
	Id     interface{} //
	Tid    interface{} // 模板id
	Cid    interface{} // 检查项id
	Sort   interface{} // 排序
	Weight interface{} // 权重
}
