// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// CronTask is the golang structure of table cron_task for DAO operations like Where/Data.
type CronTask struct {
	g.Meta      `orm:"table:cron_task, do:true"`
	Id          interface{} //
	CronUid     interface{} //
	Name        interface{} // 定时任务名称
	Content     interface{} // 定时任务内容
	CronExpr    interface{} // 定时任务表达式
	LastrunTime *gtime.Time // 最后执行时间
	NextrunTime *gtime.Time //
	Status      interface{} // 状态 running  stopped
	Creater     interface{} // 创建人
	Updater     interface{} // 更新人
	Created     *gtime.Time //
	Updated     *gtime.Time //
	Type        interface{} // 任务类型
}
