// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Script is the golang structure of table script for DAO operations like Where/Data.
type Script struct {
	g.Meta    `orm:"table:script, do:true"`
	Id        interface{} //
	Name      interface{} // 命令名称
	Content   interface{} // 脚本内容
	Args      interface{} // 参数信息
	Desc      interface{} // 描述信息
	Type      interface{} // 脚本类型shell或者powershell
	OwnerType interface{} // 命令拥有者类型
	OwnerUid  interface{} // 拥有者uid
	Created   *gtime.Time //
	Updated   *gtime.Time //
	ScriptUid interface{} //
	WaitTime  interface{} // 脚本超时时间
	Cmd       interface{} // 脚本解释器
	Ext       interface{} // 脚本文件扩展名
}
