// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// User is the golang structure of table user for DAO operations like Where/Data.
type User struct {
	g.Meta   `orm:"table:user, do:true"`
	Id       interface{} //
	Uid      interface{} //
	Username interface{} //
	Passwd   interface{} //
	Email    interface{} //
	Created  *gtime.Time //
	Updated  *gtime.Time //
	Phone    interface{} //
	Avatar   interface{} // 头像
	Status   interface{} // 状态 1 启用 2 禁用
}
