// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Vm is the golang structure of table vm for DAO operations like Where/Data.
type Vm struct {
	g.Meta      `orm:"table:vm, do:true"`
	Id          interface{} //
	Uuid        interface{} // 主机uuid
	Name        interface{} //
	Hostname    interface{} //
	OsType      interface{} // 操作系统类型
	OsInfo      interface{} // 操作系统信息
	Hosttype    interface{} // 主机类型
	Networktype interface{} // 网络类型
	PrivateIp   interface{} //
	PublicIp    interface{} //
	Created     *gtime.Time //
	Updated     *gtime.Time //
	Creater     interface{} // 创建人
	Address     interface{} //
	PeerId      interface{} //
}
