// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// CheckTpl is the golang structure for table check_tpl.
type CheckTpl struct {
	Id          int         `json:"id"          ` //
	Tid         string      `json:"tid"         ` // 唯一id
	Name        string      `json:"name"        ` // 名称
	Description string      `json:"description" ` // 描述
	Type        string      `json:"type"        ` // 类型
	Creater     string      `json:"creater"     ` // 创建人
	Updater     string      `json:"updater"     ` // 更新人
	Created     *gtime.Time `json:"created"     ` //
	Updated     *gtime.Time `json:"updated"     ` //
}
