// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// CronTask is the golang structure for table cron_task.
type CronTask struct {
	Id          int         `json:"id"          ` //
	CronUid     string      `json:"cronUid"     ` //
	Name        string      `json:"name"        ` // 定时任务名称
	Content     string      `json:"content"     ` // 定时任务内容
	CronExpr    string      `json:"cronExpr"    ` // 定时任务表达式
	LastrunTime *gtime.Time `json:"lastrunTime" ` // 最后执行时间
	NextrunTime *gtime.Time `json:"nextrunTime" ` //
	Status      string      `json:"status"      ` // 状态 running  stopped
	Creater     string      `json:"creater"     ` // 创建人
	Updater     string      `json:"updater"     ` // 更新人
	Created     *gtime.Time `json:"created"     ` //
	Updated     *gtime.Time `json:"updated"     ` //
	Type        string      `json:"type"        ` // 任务类型
}
