// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Task is the golang structure for table task.
type Task struct {
	Id       int         `json:"id"       ` //
	TaskId   string      `json:"taskId"   ` // 任务id
	Type     string      `json:"type"     ` // 任务类型
	Content  string      `json:"content"  ` // 任务内容
	Name     string      `json:"name"     ` // 任务名称
	Reqid    string      `json:"reqid"    ` // 请求id
	ParentId string      `json:"parentId" ` //
	Status   string      `json:"status"   ` //
	Created  *gtime.Time `json:"created"  ` //
	Updated  *gtime.Time `json:"updated"  ` //
	Creater  string      `json:"creater"  ` // 创建人
}
