// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// User is the golang structure for table user.
type User struct {
	Id       int         `json:"id"       ` //
	Uid      string      `json:"uid"      ` //
	Username string      `json:"username" ` //
	Passwd   string      `json:"passwd"   ` //
	Email    string      `json:"email"    ` //
	Created  *gtime.Time `json:"created"  ` //
	Updated  *gtime.Time `json:"updated"  ` //
	Phone    string      `json:"phone"    ` //
	Avatar   string      `json:"avatar"   ` // 头像
	Status   string      `json:"status"   ` // 状态 1 启用 2 禁用
}
