// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// AgentInfo is the golang structure for table agent_info.
type AgentInfo struct {
	Id             int         `json:"id"             ` //
	Peerid         string      `json:"peerid"         ` // 节点id
	Name           string      `json:"name"           ` // agent名称
	ExpectedStatus string      `json:"expectedStatus" ` // 期望状态
	Status         string      `json:"status"         ` //
	IsDefault      int         `json:"isDefault"      ` //
	Timeout        int         `json:"timeout"        ` // 启动超时时间
	Created        *gtime.Time `json:"created"        ` //
	Updated        *gtime.Time `json:"updated"        ` //
}
