// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// CheckItem is the golang structure for table check_item.
type CheckItem struct {
	Id          int         `json:"id"          ` //
	CheckItemId string      `json:"checkItemId" ` //
	Name        string      `json:"name"        ` // 检查项名称
	Desc        string      `json:"desc"        ` // 检查项描述
	Type        string      `json:"type"        ` //
	Content     string      `json:"content"     ` // 检查项内容
	Creater     string      `json:"creater"     ` // 创建人
	Updater     string      `json:"updater"     ` // 更新人
	Created     *gtime.Time `json:"created"     ` //
	Updated     *gtime.Time `json:"updated"     ` //
}
