// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Script is the golang structure for table script.
type Script struct {
	Id        int         `json:"id"        ` //
	Name      string      `json:"name"      ` // 命令名称
	Content   string      `json:"content"   ` // 脚本内容
	Args      string      `json:"args"      ` // 参数信息
	Desc      string      `json:"desc"      ` // 描述信息
	Type      string      `json:"type"      ` // 脚本类型shell或者powershell
	OwnerType string      `json:"ownerType" ` // 命令拥有者类型
	OwnerUid  string      `json:"ownerUid"  ` // 拥有者uid
	Created   *gtime.Time `json:"created"   ` //
	Updated   *gtime.Time `json:"updated"   ` //
	ScriptUid string      `json:"scriptUid" ` //
}
