// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// CheckItemDao is the data access object for table check_item.
type CheckItemDao struct {
	table   string           // table is the underlying table name of the DAO.
	group   string           // group is the database configuration group name of current DAO.
	columns CheckItemColumns // columns contains all the column names of Table for convenient usage.
}

// CheckItemColumns defines and stores column names for table check_item.
type CheckItemColumns struct {
	Id          string //
	CheckItemId string //
	Name        string // 检查项名称
	Desc        string // 检查项描述
	Type        string //
	Content     string // 检查项内容
	Creater     string // 创建人
	Updater     string // 更新人
	Created     string //
	Updated     string //
	Weight      string // 权重
	WaitTime    string // 超时时间
	Cmd         string // 脚本执行解释器
}

//  checkItemColumns holds the columns for table check_item.
var checkItemColumns = CheckItemColumns{
	Id:          "id",
	CheckItemId: "check_item_id",
	Name:        "name",
	Desc:        "desc",
	Type:        "type",
	Content:     "content",
	Creater:     "creater",
	Updater:     "updater",
	Created:     "created",
	Updated:     "updated",
	Weight:      "weight",
	WaitTime:    "wait_time",
	Cmd:         "cmd",
}

// NewCheckItemDao creates and returns a new DAO object for table data access.
func NewCheckItemDao() *CheckItemDao {
	return &CheckItemDao{
		group:   "default",
		table:   "check_item",
		columns: checkItemColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *CheckItemDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *CheckItemDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *CheckItemDao) Columns() CheckItemColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *CheckItemDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *CheckItemDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *CheckItemDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
